services:
  portfolio-dev:
    container_name: qrius-portfolio-service
    image: qrius-portfolio
    build:
      target: dev
      context: ./applications/Qrius-Portfolio
      dockerfile: Dockerfile
    volumes:
      - ./applications/Qrius-Portfolio:/app
      - /app/node_modules
      - /app/public
    ports:
      - "3000:3000"
    profiles: [frontend-dev]

  api-v1:
    container_name: qrius-api-v1-service
    image: qrius-api-v1
    build:
      target: dev
      context: ./applications/EBPI-API
      dockerfile: Dockerfile
    ports:
      - "0:5000"
    profiles: [api-v1]
    volumes:
      - ./applications/EBPI-API:/api
    stdin_open: true
    tty: true
  
  portfolio-prod:
    container_name: qrius-portfolio-service
    image: qrius-portfolio
    build:
      target: prod
      context: ./applications/Qrius-Portfolio
      dockerfile: Dockerfile
    volumes:
      - ./applications/Qrius-Portfolio:/app
      - /app/node_modules
      - /app/public
    ports:
      - "3000:3000"
    profiles: [frontend-prod]

  nginx:
    container_name: qrius-nginx
    image: nginx-proxy
    build:
      context: ./applications/nginx-reverse-proxy
      dockerfile: Dockerfile
    volumes:
      - ./applications/nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"