services:
  portfolio-dev:
    image: qrius-portfolio
    build:
      target: dev
      context: ./applications/Qrius-Portfolio
      dockerfile: Dockerfile
    volumes:
      - ./applications/Qrius-Portfolio:/app
      - /app/node_modules
      - /app/public
    ports:
      - "3000:3000"
    profiles: [frontend-dev]
    depends_on:
      - nginx

  api-v1:
    image: qrius-api-v1
    build:
      target: dev
      context: ./applications/EBPI-API
      dockerfile: Dockerfile
    ports:
      - "0:5000"
    profiles: [api-v1]
    depends_on:
      - nginx
  
  portfolio-prod:
    image: qrius-portfolio
    build:
      target: prod
      context: ./applications/Qrius-Portfolio
      dockerfile: Dockerfile
    volumes:
      - ./applications/Qrius-Portfolio:/app
      - /app/node_modules
      - /app/public
    ports:
      - "3000:3000"
    profiles: [frontend-prod]
    depends_on:
      - nginx

  nginx:
    image: nginx-proxy
    build:
      context: ./applications/nginx-reverse-proxy
      dockerfile: Dockerfile
    volumes:
      - ./applications/nginx-reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"